# Generated by Django 5.1.5 on 2025-05-09 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_date_inscription'),
        ('moviedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['date_publication']},
        ),
        migrations.AlterModelOptions(
            name='critique',
            options={'ordering': ['-date_publication']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-date_sortie']},
        ),
        migrations.AddField(
            model_name='commentaire',
            name='est_modere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='critique',
            unique_together={('film', 'utilisateur')},
        ),
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['critique', 'date_publication'], name='moviedb_com_critiqu_72cabc_idx'),
        ),
        migrations.AddIndex(
            model_name='critique',
            index=models.Index(fields=['film', 'utilisateur'], name='moviedb_cri_film_id_c896d1_idx'),
        ),
        migrations.AddIndex(
            model_name='critique',
            index=models.Index(fields=['date_publication'], name='moviedb_cri_date_pu_58f44e_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['titre'], name='moviedb_fil_titre_e1ae83_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['genre'], name='moviedb_fil_genre_7550b9_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['date_sortie'], name='moviedb_fil_date_so_b92013_idx'),
        ),
    ]
