# Generated by Django 5.1.5 on 2025-05-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_alter_commentaire_options_alter_critique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['tmdb_id'], name='moviedb_fil_tmdb_id_ecec84_idx'),
        ),
    ]
